fix(deps): install msodbcsql18 to remote executor docker image (#3781)

diff --git a/docker/datahub-executor/Dockerfile b/docker/datahub-executor/Dockerfile
--- a/docker/datahub-executor/Dockerfile
+++ b/docker/datahub-executor/Dockerfile
@@ -39,6 +39,21 @@ RUN apt-get update -y && \
 RUN ln -svT "/usr/lib/jvm/java-17-openjdk-$(dpkg --print-architecture)" /usr/lib/jvm/default-jvm
 ENV JAVA_HOME=/usr/lib/jvm/default-jvm
 
+RUN <<EOF
+set -e
+DEBIAN_VERSION=$(cat /etc/debian_version | cut -d . -f 1)
+curl -sSL https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
+curl -sSL https://packages.microsoft.com/config/debian/$DEBIAN_VERSION/prod.list | tee /etc/apt/sources.list.d/mssql-release.list
+gpg -o /usr/share/keyrings/microsoft-prod.gpg --dearmor /etc/apt/trusted.gpg.d/microsoft.asc
+apt-get update
+ACCEPT_EULA=Y apt-get install -y -qq msodbcsql18
+rm -rf /var/lib/apt/lists/*
+
+odbcinst -j || { echo 'odbcinst -j failed'; exit 1; }
+odbcinst -q -d -n "ODBC Driver 18 for SQL Server" || { echo 'ODBC Driver 18 for SQL Server not found'; exit 1; }
+
+EOF
+
 USER datahub
 RUN uv pip install --no-cache -e .
 
