start docker

diff --git a/.github/workflows/quickstart-test.yml b/.github/workflows/quickstart-test.yml
--- a/.github/workflows/quickstart-test.yml
+++ b/.github/workflows/quickstart-test.yml
@@ -26,7 +26,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest, macos-13, macos-15]
+        # os: [ubuntu-latest, macos-13, macos-15]
+        os: [macos-13, macos-15]
         include:
           - os: macos-13
             label: macOS Intel
@@ -62,13 +63,19 @@ jobs:
 
           # Install Docker Desktop
           # Install Docker Desktop
-          brew install docker docker-compose
+          brew install --cask docker
+          brew install docker-compose
 
           # Link the Docker Compose v2 plugin so it's understood by the docker CLI
           mkdir -p ~/.docker/cli-plugins
           ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
 
-          colima start
+          # colima start
+          #brew services start docker
+          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+          open -a /Applications/Docker.app --args --unattended --accept-license
+          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
 
       - name: macOS Apple Silicon setup
         if: matrix.os == 'macos-15'
@@ -79,13 +86,15 @@ jobs:
           fi
 
           # Install Docker Desktop
-          brew install docker docker-compose
+          brew install --cask docker
+          brew install docker-compose
 
           # Link the Docker Compose v2 plugin so it's understood by the docker CLI
           mkdir -p ~/.docker/cli-plugins
           ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
 
           colima start
+          #brew services start docker
 
       - name: Install dependencies
         run: |
